services:

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
