// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test.Rabbit.Consumer.Database;

#nullable disable

namespace Test.Rabbit.Consumer.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231001194539_SeedOrganizations")]
    partial class SeedOrganizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Organizations.OrganizationDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc75b1a2-24f9-45dc-b06f-a34eb1b1e7ef"),
                            Name = "Organization 1"
                        },
                        new
                        {
                            Id = new Guid("e47c38ee-8544-40b4-8e68-83f8ddc796b9"),
                            Name = "Organization 2"
                        },
                        new
                        {
                            Id = new Guid("6d56423c-b40a-4226-8273-06d9f28bac78"),
                            Name = "Organization 3"
                        },
                        new
                        {
                            Id = new Guid("ea831b56-46bf-45c5-94dd-ef7acc8d9e28"),
                            Name = "Organization 4"
                        },
                        new
                        {
                            Id = new Guid("737731dc-b1fc-4196-9d9f-2f30566b7268"),
                            Name = "Organization 5"
                        },
                        new
                        {
                            Id = new Guid("62b6e811-e44b-4332-8356-12250262ca5d"),
                            Name = "Organization 6"
                        },
                        new
                        {
                            Id = new Guid("3e233ece-de20-49a6-83c4-a6378907e526"),
                            Name = "Organization 7"
                        },
                        new
                        {
                            Id = new Guid("d82e1801-4e0a-47c0-9677-489aac621217"),
                            Name = "Organization 8"
                        },
                        new
                        {
                            Id = new Guid("09dfb161-d57c-42e6-89fc-f231dabd2c5f"),
                            Name = "Organization 9"
                        },
                        new
                        {
                            Id = new Guid("47da97ac-b236-421b-9dac-e140dc90643a"),
                            Name = "Organization 10"
                        });
                });

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Users.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Users.UserDb", b =>
                {
                    b.HasOne("Test.Rabbit.Consumer.Database.Models.Organizations.OrganizationDb", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Organizations.OrganizationDb", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
