// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test.Rabbit.Consumer.Database;

#nullable disable

namespace Test.Rabbit.Consumer.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231001224722_SeedOrganizations")]
    partial class SeedOrganizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Organizations.OrganizationDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad1"),
                            Name = "Organization 1"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad2"),
                            Name = "Organization 2"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad3"),
                            Name = "Organization 3"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad4"),
                            Name = "Organization 4"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad5"),
                            Name = "Organization 5"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad6"),
                            Name = "Organization 6"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad7"),
                            Name = "Organization 7"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad8"),
                            Name = "Organization 8"
                        },
                        new
                        {
                            Id = new Guid("750f2041-6c70-40fc-8c21-f5dd889a6ad9"),
                            Name = "Organization 9"
                        });
                });

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Users.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Users.UserDb", b =>
                {
                    b.HasOne("Test.Rabbit.Consumer.Database.Models.Organizations.OrganizationDb", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Test.Rabbit.Consumer.Database.Models.Organizations.OrganizationDb", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
